# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Current Feed # Name of your website
tagline: Products  # Set your preferred page title
description: Current recommendations for discounted products and deals are here instantly!  # Also used as a meta description
favicon:
  path: https://i.ibb.co/SBRmBmt/favicon.png # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
  type: png # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: https://picsum.photos/200.webp # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://www.currentfeed.github.io # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
# Google Analytics
ga4: G-XXXXXXX # Google Analytics 4 ölçüm kimliği (isteğe bağlı)
# Dışlama
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]

# Sosyal Medya Bağlantıları
instagram:
  username: currentfeedorg # İnstagram kullanıcı adınızı belirtin
  
  username: Current Feed Product # Used for SEO
image:
  path: assets/images/example.jpg # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
   height: 100 # Pixels
  width: 100
  alt: logo

# Doğrulanmış Rozet Ayarı
badge:
  enable: true # Rozeti etkinleştirin veya devre dışı bırakın
  icon: ri:verified-badge-fill # Rozet için simge adını belirtin (örn. Iconify Design'dan)
  color: '#dfb221' # Rozet rengini belirtin

# Varsayılan Ayarlar
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Dışlama
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
